### ISSUE TITLE
Bugs / ToDo

### ISSUE THREAD

**Issue by BasementPilot** [Zweistein2/ProjectOmega#55]
**Kritisch**
- [x] Bei den Stammdaten funktioniert die Pagination nicht
- [x] Hilfeseite muss noch erstellt werden
- [x] Verwaltung - Neuanlage: Legt man mehrfach hintereinander mehrere PC's auf einmal an ohne die Seite zwischendrinn neuzuladen, so werden diese 2fach, 3fach, 4fach,... etc. angelegt.

**naja**
- [ ] Website Responsive
- [ ] Tooltips
- [ ] Quellcode kommentieren

**Comment by Zweistein2** [comment]
Verwaltung-Bug "gefixt", in dem ein Page-Reload nach Absenden einer Mehrfach-Neuanlage erzwungen wird.
